FROM node:lts
WORKDIR /usr/src/app

# Establece el entorno de desarrollo
ENV NODE_ENV=development

# Instala dependencias completas (incluye devDependencies)
# COPY package.json pnpm-lock.yaml ./
COPY . .

# Instala pnpm
RUN npm install -g pnpm
RUN pnpm install

# Genera los archivos de Prisma
RUN pnpx prisma generate

# Expone el puerto
EXPOSE 3000

# Corre el servidor en modo desarrollo
CMD ["pnpm", "start:dev"]
